server:
  port: 19351
  session-timeout: 30
  tomcat.uri-encoding: UTF-8

logging:
  level:
    com:
      tywl:
        apigw: debug

kafka:
  bootstrap-servers: 172.25.45.122:8423,172.25.45.140:8423,172.25.45.133:8423
  producer:
    retries: 3
    batch-size: 500
    buffer-memory: 900544320
  consumer:
    auto-offset-reset: latest
    max-poll-records: 5000
    enable-auto-commit: false
    auto-commit-interval: 60
    batch:
      concurrency: 5


